// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnrrruofqimutiqipqfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhucnJydW9mcWltdXRpcWlwcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjUyODAsImV4cCI6MjA3MjA0MTI4MH0.UQgbWnoIlYQo4rJXT9xzCA8neP_qii5sjQCfj2jQ-SA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});